In [1]:
import numpy as np

In [2]:
lst = range(10000)

In [3]:
lst

range(0, 10000)

In [5]:
import sys

In [8]:
sys.getsizeof(1)*len(lst)

280000

In [12]:
arr = np.arange(10000)


In [13]:
arr

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [14]:
arr.size*arr.itemsize

40000

In [16]:
lst1 = range(10000)
lst2 = range(100000)

In [17]:
import time

In [18]:
time.time()

1660137283.428552

In [36]:
start = time.time()
result = [(x+y) for x, y in zip(lst1, lst2)]
print((time.time()-start))

0.001035928726196289


In [31]:
arr1 = np.arange(10000)
arr2 = np.arange(10000)

In [37]:
start = time.time()
result = arr1+arr2
print((time.time()-start))

0.0010013580322265625


In [38]:
lst = []

In [40]:
for i in range(1000):
    lst.append(i)

In [41]:
lst

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,


FUNCTIONS

In [42]:
a = np.array([1, 2, 3, 4, 5, 6, 7])

In [43]:
a


array([1, 2, 3, 4, 5, 6, 7])

In [45]:
type(a
    )

numpy.ndarray

In [46]:
a.ndim

1

In [48]:
a = np.array([[1, 2, 3, 4, 5, 6], [1, 2, 3, 4, 5, 6]])

In [49]:
a.ndim

2

In [50]:
a*a

array([[ 1,  4,  9, 16, 25, 36],
       [ 1,  4,  9, 16, 25, 36]])

In [51]:
a+a

array([[ 2,  4,  6,  8, 10, 12],
       [ 2,  4,  6,  8, 10, 12]])

In [52]:
a/a

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [53]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [61]:
a = np.zeros((3, 4, 5))


In [62]:
a

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [63]:
a.ndim

3

In [64]:
np.ones((2, 2, 3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [65]:
a = np.array([2, 45, 6 ,32, 54])

In [66]:
a

array([ 2, 45,  6, 32, 54])

In [67]:
type(a
    )

numpy.ndarray

In [68]:
a.dtype

dtype('int32')

In [69]:
a.argmax

<function ndarray.argmax>

In [70]:
a.argmax()

4

In [71]:
a[a.argmax()]

54

In [72]:
a.argmin()

0

In [73]:
a.sum()

139

In [74]:
a.cumsum()

array([  2,  47,  53,  85, 139], dtype=int32)

In [75]:
a.cumprod()

array([     2,     90,    540,  17280, 933120], dtype=int32)

In [77]:
a.itemsize

4

In [78]:
a.size

5

In [79]:
a[0:3]

array([ 2, 45,  6])

In [80]:
a[0] = 1000

In [81]:
a

array([1000,   45,    6,   32,   54])

In [86]:
np.array([1,2 ,4,5], dtype = "complex")

array([1.+0.j, 2.+0.j, 4.+0.j, 5.+0.j])

In [94]:
np.linspace(2, 10, 50)

array([ 2.        ,  2.16326531,  2.32653061,  2.48979592,  2.65306122,
        2.81632653,  2.97959184,  3.14285714,  3.30612245,  3.46938776,
        3.63265306,  3.79591837,  3.95918367,  4.12244898,  4.28571429,
        4.44897959,  4.6122449 ,  4.7755102 ,  4.93877551,  5.10204082,
        5.26530612,  5.42857143,  5.59183673,  5.75510204,  5.91836735,
        6.08163265,  6.24489796,  6.40816327,  6.57142857,  6.73469388,
        6.89795918,  7.06122449,  7.2244898 ,  7.3877551 ,  7.55102041,
        7.71428571,  7.87755102,  8.04081633,  8.20408163,  8.36734694,
        8.53061224,  8.69387755,  8.85714286,  9.02040816,  9.18367347,
        9.34693878,  9.51020408,  9.67346939,  9.83673469, 10.        ])

In [95]:
np.sin(0)

0.0

In [96]:
np.sin(90)

0.8939966636005579

In [97]:
a = np.arange(12)

In [98]:
a


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [99]:
a.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [101]:
a.min()

0

In [103]:
a.max()

11

In [104]:
np.abs(5.6)

5.6

In [105]:
np.floor(5.6)

5.0

In [106]:
np.ceil(5.3)

6.0

MATPLOTLIB